name: Build IPA
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Project Config
        run: |
          echo "name: GoproStretch
          targets:
            GoproStretch:
              type: application
              platform: iOS
              deploymentTarget: '16.0'
              sources: [ContentView.swift]
              info:
                path: Info.plist" > project.yml

      - name: Generate and Build
        run: |
          brew install xcodegen
          xcodegen generate
          xcodebuild build -project GoproStretch.xcodeproj -scheme GoproStretch -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          
          mkdir -p Payload
          # Ищем приложение в папке сборки
          APP_PATH=$(find . -name "GoproStretch.app" -type d | head -n 1)
          cp -r "$APP_PATH" Payload/
          zip -r GoproStretch.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: GoproApp-kitanaizyxx
          path: GoproStretch.ipa
