name: Build IPA
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile iOS Binary
        run: |
          xcrun -sdk iphoneos swiftc ContentView.swift \
          -target arm64-apple-ios16.0 \
          -o GoproToolBin \
          -sdk $(xcrun --sdk iphoneos --show-sdk-path) \
          -emit-executable

      - name: Create IPA Structure
        run: |
          mkdir -p Payload/GoproTool.app
          mv GoproToolBin Payload/GoproTool.app/GoproTool
          cp Info.plist Payload/GoproTool.app/Info.plist
          echo "APPL????" > Payload/GoproTool.app/PkgInfo
          zip -r GoproTool.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GoproApp-kitanaizyxx
          path: GoproTool.ipa
